### ISSUE TITLE
The capability analytics_graphs:viewpages

### ISSUE THREAD

**Issue by mudrd8mz** [marceloschmitt/moodle-block_analytics_graphs#10]
- No matching string for its name
- Unable to overwrite / edit permissions in the block context
- Needs SPAM risk as it controls access to email.php

**Comment by marceloschmitt** [comment]
Fixed the first and the last items. We are unable to overwrite permissions in the block context because when the block shows its result, the has no moodle element, only the graph. Or am I missing something?

Well, is it really necessary to put the graphs inside the moodle page structure? Is that something mandatory?

**Comment by mudrd8mz** [comment]
Well. It is common in Moodle UI that certain navigation elements are always visible. How do you expect your users to go page from the graph screen?

Regarding the possibility to override permissions, I guess the reason is that the db/access.php file declares the viewpages capability with `'contextlevel' => CONTEXT_COURSE`. Is that intentional? And why?

**Comment by marceloschmitt** [comment]
I will examine the contexlevel issue. The graph is always visualized in another window. But if this is important as a way to mantain a UI identity, I may try to do that in another way.

**Comment by mudrd8mz** [comment]
It's not a blocker for the approval, of course. It just surprised me.

**Comment by marceloschmitt** [comment]
You are correct about the context. I will change it.
